# Copyright (c) 2026 Jinray Xie
# Contact: xiejinhui22@mails.ucas.ac.cn
# Source-available for non-commercial use only; commercial use requires written authorization.

from __future__ import annotations

from ..base import DataConnectorSpec, DisciplineModule, DisciplineModuleSpec, MethodTemplateSpec


class MachineLearningModule(DisciplineModule):
    spec = DisciplineModuleSpec(
        module_id="machine_learning",
        display_name="Machine learning and model evaluation",
        keywords=["machine learning", "deep learning", "transformer", "cnn", "baseline", "ablation"],
        data_roles=[
            "feature_matrix",
            "target_or_label",
            "train_validation_test_split",
            "sample_group",
            "quality_flag",
            "image_folder",
            "catalog_table",
            "pretrained_backbone",
            "embedding_matrix",
        ],
        method_families=[
            "baseline_model",
            "supervised_learning",
            "deep_learning_architecture",
            "self_supervised_representation_learning",
            "deep_learning_checkpoint_validation",
            "representation_learning_diagnostics",
            "few_label_evaluation",
            "representation_retrieval",
            "model_interpretation",
            "cross_validation",
            "ablation_study",
            "error_analysis",
        ],
        validation_checks=[
            "data_leakage_check",
            "train_validation_test_split_check",
            "baseline_comparison",
            "ablation_coverage",
            "uncertainty_or_resampling_check",
            "checkpoint_shape_check",
            "embedding_health_check",
            "few_label_protocol_check",
            "model_statistical_validity_gate",
            "interpretability_artifact_check",
        ],
        figure_families=[
            "baseline_vs_model_performance",
            "ablation_summary",
            "confusion_or_error_analysis",
            "learning_curve_or_validation_curve",
            "feature_importance_or_attention_summary",
            "model_diagnostics",
            "feature_space_structure",
        ],
        minimum_main_figures=5,
        target_main_figures=6,
        required_figure_groups=[
            "data_overview",
            "class_or_target_distribution",
            "feature_space_structure",
            "baseline_vs_model_performance",
            "ablation_or_error_analysis",
        ],
        formula_families=[
            "loss_function",
            "classification_metric",
            "cross_validation_estimator",
            "ablation_delta",
            "contrastive_or_self_distillation_loss",
            "cosine_similarity",
        ],
        reviewer_risks=[
            "missing_baseline",
            "missing_ablation",
            "data_leakage",
            "overclaiming_without_external_validation",
            "checkpoint_shape_mismatch",
            "embedding_collapse",
            "few_label_protocol_underpowered",
        ],
        code_generation_constraints=[
            "Stage-owned code layout is required: dataset preparation and split construction belong under data/scripts, while model training, evaluation, ablation, interpretation, and plotting code belongs under methods/scripts, methods/src, or methods/plotting.",
            "Methods writing must use method_formula_manifest and figure_code_trace when losses, metrics, validation estimators, ablation deltas, or generated figures are present.",
            "Require a clear label or response column before supervised model code is generated.",
            "Prefer lightweight baselines before optional deep-learning training scaffolds.",
            "Treat DINOv2 or other foundation backbones as optional project-bound dependencies, not mandatory core imports.",
            "Require embedding health diagnostics before writing representation-learning claims.",
        ],
        data_connectors=[
            DataConnectorSpec(
                connector_id="local_files",
                display_name="Local ML dataset files",
                access_modes=["local_files"],
                packages=["pandas", "numpy", "scikit-learn"],
                package_modules=["pandas", "numpy", "sklearn"],
                download_or_access=["read local train/validation/test splits", "read image folders", "read feature tables"],
                data_formats=["CSV", "Parquet", "NPY/NPZ", "image folders", "JSONL"],
                requires_credentials=False,
                template_paths=["data/connectors/local_ml_dataset.py.template"],
            ),
            DataConnectorSpec(
                connector_id="kaggle_huggingface",
                display_name="Kaggle or Hugging Face datasets",
                access_modes=["api_access", "cloud_storage"],
                packages=["kaggle", "datasets", "huggingface_hub"],
                package_modules=["kaggle", "datasets", "huggingface_hub"],
                credential_env_vars=["KAGGLE_USERNAME", "KAGGLE_KEY"],
                download_or_access=["Kaggle dataset download", "Hugging Face dataset streaming/download", "cache dataset manifest"],
                data_formats=["CSV", "Parquet", "JSONL", "image folders", "Arrow dataset cache"],
                requires_credentials=True,
                template_paths=["data/connectors/kaggle_huggingface.py.template"],
            ),
            DataConnectorSpec(
                connector_id="vision_catalog_image",
                display_name="Vision image-folder and catalog connector",
                access_modes=["local_files", "image_folder", "catalog_table"],
                packages=["astropy"],
                package_modules=["astropy"],
                download_or_access=["align image files to catalog object ids", "filter labels", "write image-label manifest"],
                data_formats=["image folder", "CSV catalog", "FITS catalog"],
                requires_credentials=False,
                template_paths=["data_connectors/vision_catalog_image/template.py"],
                fixture_paths=["data_connectors/vision_catalog_image/fixture_catalog.csv"],
                genericity_rules=["Expose object-id and label columns as parameters.", "Do not encode survey-specific folder names."],
            ),
            DataConnectorSpec(
                connector_id="pretrained_backbone",
                display_name="Pretrained backbone metadata connector",
                access_modes=["local_checkpoint", "torch_hub", "model_registry"],
                packages=["torch"],
                package_modules=["torch"],
                download_or_access=["load or document pretrained backbone source", "write checkpoint metadata", "record model family"],
                data_formats=["PyTorch checkpoint", "state_dict", "model metadata JSON"],
                requires_credentials=False,
                template_paths=["data_connectors/pretrained_backbone/template.py"],
                fixture_paths=["data_connectors/pretrained_backbone/fixture_backbone_metadata.json"],
                genericity_rules=["Record source and checkpoint provenance.", "Do not package local checkpoint files."],
            ),
            DataConnectorSpec(
                connector_id="tabular_environment_dataset",
                display_name="Tabular crop/environment dataset profiler",
                access_modes=["local_files", "server_processed_files"],
                packages=[],
                package_modules=[],
                download_or_access=["profile tabular data columns", "identify numeric feature candidates", "write dataset profile manifest"],
                data_formats=["CSV", "Parquet metadata", "dataset profile JSON"],
                requires_credentials=False,
                template_paths=["data_connectors/tabular_environment_dataset/template.py"],
                fixture_paths=["data_connectors/tabular_environment_dataset/fixture_environment_table.csv"],
                genericity_rules=["Target, feature, group, and split columns must be parameters.", "Do not encode crop, region, year, or local paths."],
            ),
            DataConnectorSpec(
                connector_id="saved_model_loader",
                display_name="Saved model manifest writer",
                access_modes=["local_model_artifact", "server_processed_files"],
                packages=["joblib", "pickle", "torch"],
                package_modules=["joblib", "pickle", "torch"],
                download_or_access=["record saved-model family", "sanitize model artifact path", "write expected feature manifest"],
                data_formats=["PKL", "Joblib", "PyTorch checkpoint", "model manifest JSON"],
                requires_credentials=False,
                template_paths=["data_connectors/saved_model_loader/template.py"],
                genericity_rules=["Do not package model binaries.", "Sanitize model paths in reusable manifests."],
            ),
        ],
        method_templates=[
            MethodTemplateSpec(
                template_id="baseline_model",
                display_name="Baseline model",
                discipline="machine_learning",
                method_family="baseline_model",
                input_roles=["feature_matrix", "target_or_label"],
                optional_roles=["sample_group", "quality_flag"],
                packages=["pandas", "numpy", "scikit-learn"],
                package_modules=["pandas", "numpy", "sklearn"],
                output_artifacts=["results/tables/baseline_metrics.csv", "results/figures/baseline_vs_model_performance.png"],
                figure_groups=["baseline_vs_model_performance"],
                formula_families=["classification_metric", "cross_validation_estimator"],
                validation_checks=["label_available", "minimum_class_count", "metric_written"],
                template_path="method_templates/baseline_model/template.py",
                aliases=["dummy baseline", "random forest baseline", "classical ml baseline"],
                variants=["dummy_classifier", "random_forest"],
                genericity_rules=["Expose target and feature columns as parameters.", "Do not hard-code dataset names or labels."],
            ),
            MethodTemplateSpec(
                template_id="ablation_study",
                display_name="Ablation study",
                discipline="machine_learning",
                method_family="ablation_study",
                input_roles=["feature_matrix", "target_or_label"],
                optional_roles=["feature_groups", "sample_group"],
                packages=["pandas", "numpy", "scikit-learn"],
                package_modules=["pandas", "numpy", "sklearn"],
                output_artifacts=["results/tables/ablation_metrics.csv", "results/figures/ablation_or_error_analysis.png"],
                figure_groups=["ablation_or_error_analysis"],
                formula_families=["ablation_delta", "classification_metric"],
                validation_checks=["feature_group_available", "baseline_comparison", "metric_written"],
                template_path="method_templates/ablation_study/template.py",
                aliases=["feature group ablation", "component ablation"],
                variants=["drop_one_group", "single_group_only"],
                genericity_rules=["Feature groups must be configuration values.", "Do not encode paper-specific feature names into the template."],
            ),
            MethodTemplateSpec(
                template_id="train_validation_test_split_check",
                display_name="Train/validation/test split check",
                discipline="machine_learning",
                method_family="data_split_validation",
                input_roles=["feature_matrix", "target_or_label", "train_validation_test_split"],
                optional_roles=["sample_group"],
                packages=["pandas", "numpy", "scikit-learn"],
                package_modules=["pandas", "numpy", "sklearn"],
                output_artifacts=["results/tables/split_integrity_report.csv", "results/figures/class_or_target_distribution.png"],
                figure_groups=["class_or_target_distribution"],
                formula_families=["split_ratio", "class_support_ratio"],
                validation_checks=["no_overlap_between_splits", "class_balance_by_split", "group_leakage_check"],
                template_path="method_templates/train_validation_test_split_check/template.py",
                aliases=["split integrity", "leakage check", "holdout split check"],
                variants=["explicit_split_column", "generated_stratified_split"],
                genericity_rules=["Split column names must be parameters.", "Never encode project-specific sample IDs."],
            ),
            MethodTemplateSpec(
                template_id="group_holdout_training_smoke_test",
                display_name="Group-held-out training smoke test",
                discipline="machine_learning",
                method_family="cross_validation",
                input_roles=["feature_matrix", "target_or_label", "sample_group"],
                optional_roles=["quality_flag", "train_validation_test_split"],
                packages=["pandas", "numpy", "scikit-learn"],
                package_modules=["pandas", "numpy", "sklearn"],
                output_artifacts=[
                    "methods/group_holdout_training_smoke_test.py",
                    "results/tables/group_holdout_smoke_metrics.csv",
                    "results/tables/training_data_completeness_report.csv",
                ],
                figure_groups=["baseline_vs_model_performance", "confusion_or_error_analysis"],
                formula_families=["classification_metric", "cross_validation_estimator"],
                validation_checks=[
                    "minimum_class_count",
                    "group_leakage_check",
                    "baseline_comparison",
                    "metric_written",
                ],
                template_path="method_templates/group_holdout_training_smoke_test/template.py",
                aliases=["source-held-out validation", "group holdout smoke test", "leakage contrast"],
                variants=["group_kfold", "event_random_contrast"],
                genericity_rules=[
                    "Group identifiers, labels, and feature columns must be parameters.",
                    "Event-random splits cannot be used as primary scientific evidence when groups exist.",
                    "Do not encode dataset-specific class names or sample ids.",
                ],
                maturity="runnable",
            ),
            MethodTemplateSpec(
                template_id="self_supervised_dino_training",
                display_name="Self-supervised DINO training plan",
                discipline="machine_learning",
                method_family="self_supervised_representation_learning",
                input_roles=["image_folder", "pretrained_backbone"],
                optional_roles=["catalog_table"],
                packages=["torch", "tensorboard"],
                package_modules=["torch", "torch.utils.tensorboard"],
                output_artifacts=["methods/src/dino_training_plan.json", "results/tables/embedding_health.csv"],
                figure_groups=["learning_curve_or_validation_curve", "model_diagnostics"],
                formula_families=["contrastive_or_self_distillation_loss"],
                validation_checks=["dataset_manifest_available", "checkpoint_manifest_written"],
                template_path="method_templates/self_supervised_dino_training/template.py",
                aliases=["DINO", "DINOv2", "self-supervised ViT", "teacher-student SSL"],
                variants=["training_plan", "project_bound_torch_training"],
                genericity_rules=["Do not hard-code image folders or checkpoint paths.", "Training execution must be project-bound and resource-aware."],
            ),
            MethodTemplateSpec(
                template_id="checkpoint_shape_adapter",
                display_name="Checkpoint shape adapter",
                discipline="machine_learning",
                method_family="deep_learning_checkpoint_validation",
                input_roles=["pretrained_backbone"],
                optional_roles=["image_folder"],
                packages=["torch"],
                package_modules=["torch"],
                output_artifacts=["results/tables/checkpoint_shape_report.json"],
                figure_groups=["model_diagnostics"],
                formula_families=["token_grid_shape"],
                validation_checks=["checkpoint_shape_check", "position_embedding_resize_candidate"],
                template_path="method_templates/checkpoint_shape_adapter/template.py",
                aliases=["position embedding resize", "state_dict adapter", "checkpoint compatibility"],
                variants=["shape_report", "pos_embedding_resize_plan"],
                genericity_rules=["Compare shapes before loading weights.", "Never upload local checkpoint binaries."],
            ),
            MethodTemplateSpec(
                template_id="embedding_extraction_health_diagnostics",
                display_name="Embedding extraction health diagnostics",
                discipline="machine_learning",
                method_family="representation_learning_diagnostics",
                input_roles=["embedding_matrix"],
                optional_roles=["target_or_label"],
                packages=[],
                package_modules=[],
                output_artifacts=["results/tables/embedding_health.csv", "results/figures/feature_space_structure.png"],
                figure_groups=["feature_space_structure", "model_diagnostics"],
                formula_families=["embedding_norm", "variance_diagnostics"],
                validation_checks=["embedding_health_check", "collapse_check", "metric_written"],
                template_path="method_templates/embedding_extraction_health_diagnostics/template.py",
                aliases=["embedding health", "collapse diagnostics", "representation diagnostics"],
                variants=["csv_embedding_matrix"],
                genericity_rules=["Embedding columns must be parameterized.", "Report collapse risk before representation claims."],
            ),
            MethodTemplateSpec(
                template_id="few_label_probe_benchmark",
                display_name="Few-label probe benchmark",
                discipline="machine_learning",
                method_family="few_label_evaluation",
                input_roles=["embedding_matrix", "target_or_label"],
                optional_roles=["train_validation_test_split", "pretrained_backbone"],
                packages=["scikit-learn"],
                package_modules=["sklearn"],
                output_artifacts=["results/tables/few_label_probe_summary.csv", "results/figures/baseline_vs_model_performance.png"],
                figure_groups=["baseline_vs_model_performance", "learning_curve_or_validation_curve"],
                formula_families=["classification_metric", "class_support_ratio"],
                validation_checks=["few_label_protocol_check", "multi_seed_summary", "baseline_comparison"],
                template_path="method_templates/few_label_probe_benchmark/template.py",
                aliases=["few-shot probe", "linear probe", "MLP probe", "few-label benchmark"],
                variants=["aggregate_existing_runs", "project_bound_probe_training"],
                genericity_rules=["Fractions and seeds must be parameters.", "Compare against random or classical baselines."],
            ),
            MethodTemplateSpec(
                template_id="embedding_similarity_retrieval",
                display_name="Embedding similarity retrieval",
                discipline="machine_learning",
                method_family="representation_retrieval",
                input_roles=["embedding_matrix"],
                optional_roles=["catalog_table", "quality_flag"],
                packages=[],
                package_modules=[],
                output_artifacts=["results/tables/similarity_retrieval.csv", "results/figures/confusion_or_error_analysis.png"],
                figure_groups=["feature_space_structure", "confusion_or_error_analysis"],
                formula_families=["cosine_similarity"],
                validation_checks=["query_sample_available", "retrieval_table_written"],
                template_path="method_templates/embedding_similarity_retrieval/template.py",
                aliases=["embedding retrieval", "similarity search", "nearest neighbor retrieval"],
                variants=["cosine_topk"],
                genericity_rules=["Expose query id and embedding columns as parameters.", "Do not encode specific object ids."],
            ),
            MethodTemplateSpec(
                template_id="random_forest_regression_gridsearch",
                display_name="Random forest regression grid search",
                discipline="machine_learning",
                method_family="supervised_learning",
                input_roles=["feature_matrix", "target_or_label"],
                optional_roles=["sample_group", "train_validation_test_split"],
                packages=["scikit-learn"],
                package_modules=["sklearn"],
                output_artifacts=["methods/src/random_forest_regression.py", "results/tables/random_forest_metrics.csv"],
                figure_groups=["baseline_vs_model_performance", "feature_importance_or_attention_summary"],
                formula_families=["ensemble_prediction", "cross_validation_estimator"],
                validation_checks=["baseline_comparison", "metric_written", "data_leakage_check"],
                template_path="method_templates/random_forest_regression_gridsearch/template.py",
                aliases=["random forest regression", "RF grid search", "tree ensemble baseline"],
                variants=["gridsearch_cv"],
                genericity_rules=["Target, features, groups, and hyperparameter grid must be configurable."],
            ),
            MethodTemplateSpec(
                template_id="xgboost_optuna_regression",
                display_name="XGBoost Optuna regression",
                discipline="machine_learning",
                method_family="supervised_learning",
                input_roles=["feature_matrix", "target_or_label"],
                optional_roles=["sample_group", "train_validation_test_split"],
                packages=["xgboost", "optuna", "scikit-learn"],
                package_modules=["xgboost", "optuna", "sklearn"],
                output_artifacts=["methods/src/xgboost_optuna_regression.py", "results/tables/xgboost_metrics.csv"],
                figure_groups=["baseline_vs_model_performance", "feature_importance_or_attention_summary"],
                formula_families=["boosted_tree_objective", "hyperparameter_optimization"],
                validation_checks=["baseline_comparison", "metric_written", "overfitting_gap_check"],
                template_path="method_templates/xgboost_optuna_regression/template.py",
                aliases=["XGBoost", "Optuna tuning", "boosted tree regression"],
                variants=["optuna_search"],
                genericity_rules=["Search space, trials, target, and features must be parameters."],
            ),
            MethodTemplateSpec(
                template_id="gradient_boosting_regression_pipeline",
                display_name="Gradient boosting regression pipeline",
                discipline="machine_learning",
                method_family="supervised_learning",
                input_roles=["feature_matrix", "target_or_label"],
                optional_roles=["train_validation_test_split"],
                packages=["scikit-learn"],
                package_modules=["sklearn"],
                output_artifacts=["methods/src/gradient_boosting_regression.py", "results/tables/gradient_boosting_metrics.csv"],
                figure_groups=["baseline_vs_model_performance"],
                formula_families=["boosting_additive_model"],
                validation_checks=["baseline_comparison", "metric_written"],
                template_path="method_templates/gradient_boosting_regression_pipeline/template.py",
                aliases=["GBDT", "gradient boosting", "classical boosting baseline"],
                variants=["sklearn_gradient_boosting"],
                genericity_rules=["Use as a configurable classical ensemble baseline."],
            ),
            MethodTemplateSpec(
                template_id="stacking_regression_ensemble",
                display_name="Stacking regression ensemble",
                discipline="machine_learning",
                method_family="supervised_learning",
                input_roles=["feature_matrix", "target_or_label"],
                optional_roles=["train_validation_test_split", "sample_group"],
                packages=["scikit-learn"],
                package_modules=["sklearn"],
                output_artifacts=["methods/src/stacking_regression.py", "results/tables/stacking_metrics.csv"],
                figure_groups=["baseline_vs_model_performance", "ablation_or_error_analysis"],
                formula_families=["stacked_generalization", "out_of_fold_prediction"],
                validation_checks=["base_model_metrics_available", "ensemble_gain_check", "data_leakage_check"],
                template_path="method_templates/stacking_regression_ensemble/template.py",
                aliases=["stacking ensemble", "stacked regression", "ensemble learning"],
                variants=["out_of_fold_stacking"],
                genericity_rules=["Require base-model metrics before claiming ensemble gain."],
            ),
            MethodTemplateSpec(
                template_id="observed_predicted_scatter_grid",
                display_name="Observed-predicted scatter grid",
                discipline="machine_learning",
                method_family="error_analysis",
                input_roles=["target_or_label", "model_prediction"],
                optional_roles=["train_validation_test_split", "sample_group"],
                packages=[],
                package_modules=[],
                output_artifacts=["results/tables/observed_predicted_metrics.csv", "results/figures/observed_predicted_scatter_grid.png"],
                figure_groups=["baseline_vs_model_performance", "model_diagnostics"],
                formula_families=["r2", "mae", "rmse"],
                validation_checks=["observed_predicted_pairs_available", "metric_written"],
                template_path="method_templates/observed_predicted_scatter_grid/template.py",
                fixture_paths=["method_templates/observed_predicted_scatter_grid/fixture_predictions.csv"],
                aliases=["observed predicted scatter", "prediction diagnostics", "model fit scatter"],
                variants=["metric_writer"],
                genericity_rules=["Observed and predicted columns must be parameters."],
            ),
            MethodTemplateSpec(
                template_id="feature_importance_report",
                display_name="Feature importance report",
                discipline="machine_learning",
                method_family="model_interpretation",
                input_roles=["feature_matrix", "model_artifact"],
                packages=[],
                package_modules=[],
                output_artifacts=["results/tables/feature_importance.csv", "results/figures/feature_importance_or_attention_summary.png"],
                figure_groups=["feature_importance_or_attention_summary"],
                formula_families=["normalized_importance"],
                validation_checks=["feature_names_available", "importance_scores_available"],
                template_path="method_templates/feature_importance_report/template.py",
                aliases=["feature importance", "model interpretation", "variable importance"],
                variants=["score_normalization"],
                genericity_rules=["Feature names and scores must be parameterized."],
            ),
            MethodTemplateSpec(
                template_id="partial_dependence_ice_analysis",
                display_name="Partial dependence and ICE analysis plan",
                discipline="machine_learning",
                method_family="model_interpretation",
                input_roles=["feature_matrix", "model_artifact"],
                optional_roles=["target_or_label"],
                packages=["scikit-learn", "matplotlib"],
                package_modules=["sklearn", "matplotlib"],
                output_artifacts=["results/tables/partial_dependence.csv", "results/figures/partial_dependence_ice.png"],
                figure_groups=["feature_importance_or_attention_summary", "model_diagnostics"],
                formula_families=["partial_dependence", "individual_conditional_expectation"],
                validation_checks=["selected_features_declared", "interpretability_artifact_check"],
                template_path="method_templates/partial_dependence_ice_analysis/template.py",
                aliases=["PDP", "ICE", "partial dependence"],
                variants=["plan_only", "project_bound_execution"],
                genericity_rules=["Select features from reviewer or method context, not fixed project fields."],
            ),
            MethodTemplateSpec(
                template_id="shap_tree_explainer_report",
                display_name="SHAP tree explainer report plan",
                discipline="machine_learning",
                method_family="model_interpretation",
                input_roles=["feature_matrix", "model_artifact"],
                optional_roles=["target_or_label"],
                packages=["shap", "matplotlib"],
                package_modules=["shap", "matplotlib"],
                output_artifacts=["results/tables/shap_summary.csv", "results/figures/shap_summary.png"],
                figure_groups=["feature_importance_or_attention_summary", "model_diagnostics"],
                formula_families=["shap_additive_explanation"],
                validation_checks=["selected_features_declared", "interpretability_artifact_check"],
                template_path="method_templates/shap_tree_explainer_report/template.py",
                aliases=["SHAP", "tree explainer", "SHAP summary"],
                variants=["plan_only", "project_bound_execution"],
                genericity_rules=["Treat SHAP as optional when package/runtime is unavailable."],
            ),
        ],
        review_rule_groups=[
            {
                "rule_group_id": "model_statistical_validity_gate",
                "display_name": "Model statistical validity gate",
                "checks": ["minimum_r2", "maximum_p_value", "minimum_sample_count", "generalization_gap"],
                "template_path": "review_rules/model_statistical_validity_gate/template.py",
                "notes": [
                    "Use p-value for statistical confidence and R2 or task metric for model fit.",
                    "Apply only when the method reports the relevant metric."
                ],
            }
        ],
    )


MODULE = MachineLearningModule()
