# Copyright (c) 2026 Jinray Xie
# Contact: xiejinhui22@mails.ucas.ac.cn
# Source-available for non-commercial use only; commercial use requires written authorization.

from __future__ import annotations

from ..base import DataConnectorSpec, DisciplineModule, DisciplineModuleSpec, MethodTemplateSpec


class GeographyModule(DisciplineModule):
    spec = DisciplineModuleSpec(
        module_id="geography",
        display_name="Geography, GIS, and remote sensing",
        keywords=["geography", "gis", "remote sensing", "ndvi", "spatial", "raster", "zoning"],
        data_roles=[
            "analysis_ready_table",
            "spatial_group_or_coordinates",
            "temporal_window",
            "remote_sensing_index",
            "environmental_covariates",
            "quality_flag",
        ],
        method_families=[
            "spatial_exploratory_analysis",
            "remote_sensing_feature_reconstruction",
            "environmental_driver_analysis",
            "spatial_block_validation",
            "baseline_ablation",
        ],
        validation_checks=[
            "coordinate_or_spatial_group_available",
            "temporal_leakage_check",
            "spatial_block_or_region_holdout",
            "missingness_and_quality_mask_check",
        ],
        figure_families=[
            "spatial_distribution_map_or_proxy",
            "remote_sensing_index_distribution",
            "environmental_driver_response",
            "spatial_block_validation_summary",
            "feature_ablation_summary",
        ],
        minimum_main_figures=5,
        target_main_figures=6,
        required_figure_groups=[
            "data_overview",
            "remote_sensing_index_distribution",
            "environmental_driver_response",
            "predictor_correlation_structure",
            "spatial_or_validation_summary",
        ],
        formula_families=["pearson_correlation", "linear_response_r2", "spatial_group_holdout", "feature_ablation_delta"],
        reviewer_risks=[
            "weak_statistical_association_without_qc",
            "spatial_autocorrelation_or_leakage",
            "unclear_remote_sensing_preprocessing",
            "missing_external_or_spatial_validation",
        ],
        code_generation_constraints=[
            "Prefer processed analysis tables when raw rasters or cloud data are unavailable locally.",
            "Require spatial coordinates or region groups before claiming spatial generalization.",
            "If spatial roles are missing, generate only non-spatial exploratory analysis and emit a blocked rescue task.",
        ],
        data_connectors=[
            DataConnectorSpec(
                connector_id="google_earth_engine",
                display_name="Google Earth Engine remote-sensing catalog",
                access_modes=["api_access", "cloud_processing"],
                packages=["earthengine-api", "geemap"],
                package_modules=["ee", "geemap"],
                credential_env_vars=["GOOGLE_APPLICATION_CREDENTIALS"],
                download_or_access=["Earth Engine image collection query", "server-side raster reduction", "export table/image to Drive or Cloud Storage"],
                data_formats=["GeoTIFF", "CSV zonal statistics", "NetCDF-like image exports", "asset manifest"],
                requires_credentials=True,
                template_paths=["data/connectors/google_earth_engine.py.template"],
            ),
            DataConnectorSpec(
                connector_id="local_raster_vector",
                display_name="Local raster/vector parser",
                access_modes=["local_files"],
                packages=["rasterio", "geopandas", "xarray", "netCDF4"],
                package_modules=["rasterio", "geopandas", "xarray", "netCDF4"],
                download_or_access=["read GeoTIFF/NetCDF rasters", "read Shapefile/GeoJSON/GeoPackage vectors", "derive zonal summaries"],
                data_formats=["GeoTIFF", "NetCDF", "Shapefile", "GeoJSON", "GeoPackage", "CSV"],
                requires_credentials=False,
                template_paths=["data/connectors/local_raster_vector.py.template"],
            ),
            DataConnectorSpec(
                connector_id="google_earth_engine_precip_export",
                display_name="Google Earth Engine precipitation export planner",
                access_modes=["api_access", "cloud_processing", "user_confirmed_export"],
                packages=["earthengine-api", "geemap"],
                package_modules=["ee", "geemap"],
                credential_env_vars=["GOOGLE_APPLICATION_CREDENTIALS"],
                download_or_access=["build precipitation collection query", "prepare monthly/seasonal reducer", "write user-confirmed export manifest"],
                data_formats=["GeoTIFF", "CSV zonal statistics", "export manifest JSON"],
                requires_credentials=True,
                template_paths=["data_connectors/google_earth_engine_precip_export/template.py"],
                fixture_paths=[],
                genericity_rules=["Parameterize collection, region, reducer, scale, and date range.", "Do not hard-code local paths or private assets."],
            ),
            DataConnectorSpec(
                connector_id="netcdf_to_geotiff_converter",
                display_name="NetCDF to GeoTIFF conversion planner",
                access_modes=["local_files", "server_processed_files"],
                packages=["xarray", "rasterio", "netCDF4"],
                package_modules=["xarray", "rasterio", "netCDF4"],
                download_or_access=["inspect NetCDF variable and coordinates", "plan GeoTIFF export", "record conversion manifest"],
                data_formats=["NetCDF", "GeoTIFF", "conversion manifest JSON"],
                requires_credentials=False,
                template_paths=["data_connectors/netcdf_to_geotiff_converter/template.py"],
                genericity_rules=["Expose variable, coordinate, CRS, and nodata parameters.", "Do not encode a dataset provider."],
            ),
            DataConnectorSpec(
                connector_id="gridded_text_to_geotiff_converter",
                display_name="Gridded text to GeoTIFF conversion helper",
                access_modes=["local_files", "server_processed_files"],
                packages=["numpy", "rasterio"],
                package_modules=["numpy", "rasterio"],
                download_or_access=["reshape gridded text values", "plan raster export", "record grid manifest"],
                data_formats=["TXT", "CSV", "GeoTIFF", "grid manifest JSON"],
                requires_credentials=False,
                template_paths=["data_connectors/gridded_text_to_geotiff_converter/template.py"],
                genericity_rules=["Parameterize grid shape, CRS, affine transform, and nodata handling."],
            ),
            DataConnectorSpec(
                connector_id="arcgis_zonal_statistics_adapter",
                display_name="ArcGIS zonal statistics adapter",
                access_modes=["desktop_gis_runtime", "server_processed_files"],
                packages=["arcpy"],
                package_modules=["arcpy"],
                download_or_access=["record zonal statistics job", "bind raster variable and zone id", "write project-bound execution manifest"],
                data_formats=["GeoTIFF", "Shapefile", "GeoPackage", "CSV zonal statistics"],
                requires_credentials=False,
                template_paths=["data_connectors/arcgis_zonal_statistics_adapter/template.py"],
                genericity_rules=["Do not require ArcGIS at import time.", "Parameterize raster variable, zone field, and requested statistics."],
            ),
        ],
        method_templates=[
            MethodTemplateSpec(
                template_id="remote_sensing_feature_reconstruction",
                display_name="Remote-sensing feature reconstruction",
                discipline="geography",
                method_family="remote_sensing_feature_reconstruction",
                input_roles=["analysis_ready_table", "remote_sensing_index", "target_or_response"],
                optional_roles=["temporal_window", "quality_flag", "environmental_covariates"],
                packages=["pandas", "numpy"],
                package_modules=["pandas", "numpy"],
                output_artifacts=["results/tables/remote_sensing_feature_summary.csv", "results/figures/remote_sensing_feature_response.png"],
                figure_groups=["remote_sensing_index_distribution", "environmental_driver_response"],
                formula_families=["linear_response_r2", "pearson_correlation"],
                validation_checks=["minimum_row_count", "missingness_check", "range_check"],
                template_path="method_templates/remote_sensing_feature_reconstruction/template.py",
                aliases=["vegetation index reconstruction", "remote sensing feature rebuild"],
                variants=["tabular_index_summary"],
                genericity_rules=["Do not hard-code a region, date range, or satellite dataset.", "Expose index, target, grouping, and quality columns as parameters."],
            ),
            MethodTemplateSpec(
                template_id="spatial_block_validation",
                display_name="Spatial block validation",
                discipline="geography",
                method_family="spatial_validation",
                input_roles=["analysis_ready_table", "target_or_response", "predictors", "spatial_group_or_coordinates"],
                optional_roles=["temporal_window", "quality_flag"],
                packages=["pandas", "numpy", "scikit-learn"],
                package_modules=["pandas", "numpy", "sklearn"],
                output_artifacts=["results/tables/spatial_validation_metrics.csv", "results/figures/spatial_or_validation_summary.png"],
                figure_groups=["spatial_or_validation_summary"],
                formula_families=["spatial_group_holdout", "validation_metric"],
                validation_checks=["minimum_group_count", "no_group_leakage", "metric_written"],
                template_path="method_templates/spatial_block_validation/template.py",
                aliases=["regional blocked validation", "leave region out validation", "spatial holdout"],
                variants=["group_kfold", "leave_one_region_out"],
                genericity_rules=["Do not hard-code study units.", "Spatial group columns must be parameters."],
            ),
            MethodTemplateSpec(
                template_id="monthly_remote_sensing_index_summary",
                display_name="Monthly remote-sensing index summary",
                discipline="geography",
                method_family="remote_sensing_feature_reconstruction",
                input_roles=["analysis_ready_table", "remote_sensing_index", "temporal_window"],
                optional_roles=["quality_flag", "spatial_group_or_coordinates"],
                packages=[],
                package_modules=[],
                output_artifacts=["results/tables/monthly_remote_sensing_index_summary.csv"],
                figure_groups=["remote_sensing_index_distribution", "data_overview"],
                formula_families=["monthly_mean", "within_month_variability"],
                validation_checks=["month_column_available", "numeric_index_columns_available"],
                template_path="method_templates/monthly_remote_sensing_index_summary/template.py",
                fixture_paths=["method_templates/monthly_remote_sensing_index_summary/fixture_monthly_indices.csv"],
                aliases=["monthly NDVI summary", "remote sensing monthly summary", "vegetation index monthly statistics"],
                variants=["single_index", "multi_index"],
                genericity_rules=["Month and index columns must be parameters.", "Do not encode crop, region, or date windows."],
            ),
            MethodTemplateSpec(
                template_id="phenology_curve_smoothing",
                display_name="Phenology curve smoothing",
                discipline="geography",
                method_family="remote_sensing_feature_reconstruction",
                input_roles=["analysis_ready_table", "remote_sensing_index", "temporal_window"],
                optional_roles=["quality_flag", "spatial_group_or_coordinates"],
                packages=[],
                package_modules=[],
                output_artifacts=["results/tables/phenology_curve_smoothing.csv"],
                figure_groups=["remote_sensing_index_distribution"],
                formula_families=["moving_average_smoothing", "peak_timing"],
                validation_checks=["ordered_time_axis_available", "smoothing_window_declared"],
                template_path="method_templates/phenology_curve_smoothing/template.py",
                fixture_paths=["method_templates/phenology_curve_smoothing/fixture_curve.csv"],
                aliases=["phenology smoothing", "vegetation curve smoothing", "NDVI seasonal curve"],
                variants=["moving_average"],
                genericity_rules=["Expose time, value, and smoothing window as parameters."],
            ),
            MethodTemplateSpec(
                template_id="ndvi_temporal_kmeans_zoning",
                display_name="NDVI temporal K-means zoning",
                discipline="geography",
                method_family="spatial_exploratory_analysis",
                input_roles=["analysis_ready_table", "remote_sensing_index"],
                optional_roles=["spatial_group_or_coordinates", "temporal_window"],
                packages=[],
                package_modules=[],
                output_artifacts=["results/tables/ndvi_temporal_kmeans_zoning.csv"],
                figure_groups=["spatial_or_validation_summary", "remote_sensing_index_distribution"],
                formula_families=["euclidean_distance", "cluster_centroid"],
                validation_checks=["feature_columns_available", "cluster_count_declared"],
                template_path="method_templates/ndvi_temporal_kmeans_zoning/template.py",
                fixture_paths=["method_templates/ndvi_temporal_kmeans_zoning/fixture_profiles.csv"],
                aliases=["temporal zoning", "NDVI clustering", "remote sensing zoning"],
                variants=["deterministic_kmeans"],
                genericity_rules=["Expose feature columns and cluster count.", "Do not encode study-area sample ids."],
            ),
            MethodTemplateSpec(
                template_id="ndvi_cluster_statistical_diagnostics",
                display_name="NDVI cluster statistical diagnostics",
                discipline="geography",
                method_family="environmental_driver_analysis",
                input_roles=["analysis_ready_table", "target_or_response"],
                optional_roles=["spatial_group_or_coordinates", "quality_flag"],
                packages=[],
                package_modules=[],
                output_artifacts=["results/tables/ndvi_cluster_statistical_diagnostics.json"],
                figure_groups=["spatial_or_validation_summary", "environmental_driver_response"],
                formula_families=["descriptive_cluster_statistics"],
                validation_checks=["cluster_column_available", "response_column_available", "formal_test_assumptions_declared"],
                template_path="method_templates/ndvi_cluster_statistical_diagnostics/template.py",
                fixture_paths=["method_templates/ndvi_cluster_statistical_diagnostics/fixture_cluster_values.csv"],
                aliases=["cluster diagnostics", "zoning statistical diagnostics", "remote sensing cluster statistics"],
                variants=["descriptive_first"],
                genericity_rules=["Separate descriptive diagnostics from formal tests requiring scipy or statsmodels."],
            ),
        ],
    )


MODULE = GeographyModule()
