# Copyright (c) 2026 xiejhhhhhh
# Contact: xiejinhui22@mails.ucas.ac.cn
# Source-available for non-commercial use only; commercial use requires written authorization.

from __future__ import annotations

from ..base import DataConnectorSpec, DisciplineModule, DisciplineModuleSpec, MethodTemplateSpec


class AstronomyModule(DisciplineModule):
    spec = DisciplineModuleSpec(
        module_id="astronomy",
        display_name="Astronomy and astrophysics",
        keywords=["astronomy", "astrophysics", "light curve", "x-ray", "catalog", "transient", "multiwavelength"],
        data_roles=[
            "source_catalog",
            "light_curve_or_time_series",
            "spectral_or_hardness_features",
            "multiwavelength_crossmatch",
            "class_label",
            "observation_quality_flag",
        ],
        method_families=[
            "catalog_crossmatch",
            "time_series_feature_extraction",
            "time_series_deep_learning_input",
            "source_classification",
            "multimodal_fusion",
            "rare_class_validation",
        ],
        validation_checks=[
            "label_leakage_check",
            "class_imbalance_check",
            "survey_or_field_holdout",
            "cadence_and_missingness_check",
            "remote_data_provenance_check",
            "event_level_completeness_check",
        ],
        figure_families=[
            "catalog_coverage_summary",
            "light_curve_feature_distribution",
            "classification_performance_summary",
            "confusion_or_error_analysis",
            "multimodal_feature_contribution",
            "transformer_input_completeness",
        ],
        minimum_main_figures=5,
        target_main_figures=6,
        required_figure_groups=[
            "data_overview",
            "catalog_or_sample_coverage",
            "time_series_or_feature_distribution",
            "classification_or_metric_summary",
            "multimodal_or_error_analysis",
        ],
        formula_families=[
            "classification_metric",
            "time_series_feature",
            "crossmatch_radius",
            "class_support_ratio",
            "sequence_tokenization",
        ],
        reviewer_risks=[
            "unverified_catalog_crossmatch",
            "class_imbalance_underreported",
            "cadence_bias_or_selection_effect",
            "remote_product_manifest_incomplete",
            "api_credential_or_reproducibility_gap",
            "missing_external_survey_validation",
        ],
        code_generation_constraints=[
            "Treat remote mission APIs and server manifests as data connectors, not mandatory package dependencies.",
            "Require explicit class labels before supervised source-classification claims.",
        ],
        data_connectors=[
            DataConnectorSpec(
                connector_id="einstein_probe_photon_api",
                display_name="Einstein Probe photon API connector",
                access_modes=["api_access", "light_curve_query"],
                packages=["requests"],
                package_modules=["requests"],
                credential_env_vars=["EP_BASE_URL", "EP_EMAIL", "EP_PASSWORD"],
                download_or_access=["query photon light curves by RA/Dec", "cache raw photon JSON", "write normalized LC and GTI tables"],
                data_formats=["JSON photon payload", "CSV light curve", "CSV GTI"],
                requires_credentials=True,
                template_paths=["data_connectors/einstein_probe_photon_api/template.py"],
                fixture_paths=["data_connectors/einstein_probe_photon_api/fixture_photon_payload.json"],
                genericity_rules=["Read credentials from environment variables only.", "Do not store project API accounts in plugin files."],
            ),
            DataConnectorSpec(
                connector_id="wxt_manifest_product",
                display_name="WXT manifest and product path connector",
                access_modes=["remote_manifest", "instrument_archive"],
                packages=[],
                package_modules=[],
                download_or_access=["build WXT product ids", "standardize server product paths", "write event-level product manifest"],
                data_formats=["manifest CSV", "server product paths", "FITS-in-ZIP inventory"],
                requires_credentials=False,
                template_paths=["data_connectors/wxt_manifest_product/template.py"],
                fixture_paths=["data_connectors/wxt_manifest_product/fixture_wxt_manifest.csv"],
                genericity_rules=["Expose server root as a parameter.", "Do not encode source ids, date ranges, or local folders."],
            ),
            DataConnectorSpec(
                connector_id="mission_archive_api",
                display_name="Mission/archive API access",
                access_modes=["api_access", "instrument_archive"],
                packages=["astroquery", "astropy", "requests"],
                package_modules=["astroquery", "astropy", "requests"],
                download_or_access=["query mission catalogs", "download table products", "retrieve light-curve or event-list metadata"],
                data_formats=["FITS", "VOTable", "CSV", "ECSV", "JSON catalog metadata"],
                requires_credentials=False,
            ),
            DataConnectorSpec(
                connector_id="remote_server_ssh",
                display_name="Remote server or instrument archive workspace",
                access_modes=["remote_server_ssh"],
                packages=["paramiko", "scp"],
                package_modules=["paramiko", "scp"],
                credential_env_vars=["DRAFTPAPER_SSH_HOST", "DRAFTPAPER_SSH_USER"],
                download_or_access=["create remote file manifest", "run server-side preprocessing", "download processed tables and figures"],
                data_formats=["remote manifest CSV", "FITS", "CSV", "Parquet", "PNG"],
                requires_credentials=True,
            ),
        ],
        method_templates=[
            MethodTemplateSpec(
                template_id="long_term_light_curve_feature_extraction",
                display_name="Long-term light-curve feature extraction",
                discipline="astronomy",
                method_family="time_series_feature_extraction",
                input_roles=["light_curve_or_time_series", "source_catalog"],
                optional_roles=["observation_quality_flag"],
                packages=[],
                package_modules=[],
                output_artifacts=["results/tables/light_curve_features.csv", "results/figures/light_curve_feature_distribution.png"],
                figure_groups=["time_series_or_feature_distribution"],
                formula_families=["time_series_feature"],
                validation_checks=["cadence_and_missingness_check", "metric_written"],
                template_path="method_templates/long_term_light_curve_feature_extraction/template.py",
                aliases=["long-term light curve", "photon lc feature", "x-ray variability feature"],
                variants=["source_level_summary", "event_level_summary"],
                genericity_rules=["Expose time, flux, and exposure columns as parameters.", "Do not encode mission-specific source classes."],
            ),
            MethodTemplateSpec(
                template_id="event_level_transformer_input_builder",
                display_name="Event-level transformer input builder",
                discipline="astronomy",
                method_family="time_series_deep_learning_input",
                input_roles=["light_curve_or_time_series", "source_catalog", "class_label"],
                optional_roles=["observation_quality_flag", "spectral_or_hardness_features"],
                packages=[],
                package_modules=[],
                output_artifacts=["data/processed/event_level_transformer_dataset.csv", "data/processed/transformer_data_completeness_report.csv"],
                figure_groups=["data_overview", "transformer_input_completeness"],
                formula_families=["sequence_tokenization", "class_support_ratio"],
                validation_checks=["event_level_completeness_check", "class_imbalance_check", "no_missing_source_features"],
                template_path="method_templates/event_level_transformer_input_builder/template.py",
                aliases=["transformer input", "sequence token table", "event-level dataset"],
                variants=["event_source_join", "source_sequence_tokens"],
                genericity_rules=["Expose source and event key columns as parameters.", "Write completeness reports before model training."],
            ),
        ],
    )


MODULE = AstronomyModule()
