"""Generate product-facing command risk documentation from CommandSpec."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from draftpaper_cli.command_registry import COMMAND_SPECS


RISK_BOUNDARIES = {
    "read": "Read-only inspection; no project mutation.",
    "write_project": "Writes only declared project artifacts and remains subject to write-set verification.",
    "network_external": "May contact an approved external provider under URL, credential and redaction policy.",
    "execute_science": "May execute confined project scientific code and declared outputs.",
    "human_checkpoint": "Requires explicit human confirmation and is excluded from unattended MCP execution.",
    "destructive_admin": "Administrative state change requiring explicit protection and recovery evidence.",
}


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_command_risk_matrix() -> str:
    counts = Counter(spec.risk_level for spec in COMMAND_SPECS.values())
    lines = [
        "# Draftpaper-loop Command Risk Matrix",
        "",
        "> Generated by `python tools/generate_product_docs.py`. Command risk is sourced from `CommandSpec`, not maintained in this document.",
        "",
        f"The current control plane contains {len(COMMAND_SPECS)} commands.",
        "",
        "## Risk Classes",
        "",
        "| Risk | Count | Default boundary |",
        "|---|---:|---|",
    ]
    for risk, count in sorted(counts.items()):
        lines.append(f"| `{_cell(risk)}` | {count} | {_cell(RISK_BOUNDARIES.get(risk, 'Explicit CommandSpec policy.'))} |")
    lines.extend((
        "",
        "## Commands",
        "",
        "| Command | Risk | Stage | Mutates | Confirmation | Resource | MCP | Declared write roots |",
        "|---|---|---|---:|---|---|---:|---|",
    ))
    for name, spec in sorted(COMMAND_SPECS.items()):
        writes = ", ".join(f"`{item}`" for item in spec.allowed_write_globs[:5]) or "none"
        if len(spec.allowed_write_globs) > 5:
            writes += f" (+{len(spec.allowed_write_globs) - 5})"
        lines.append(
            "| "
            + " | ".join((
                f"`{_cell(name)}`",
                f"`{_cell(spec.risk_level)}`",
                _cell(spec.formal_stage),
                "yes" if spec.mutates_project else "no",
                _cell(spec.confirmation_policy),
                _cell(spec.resource_class),
                "yes" if spec.mcp_exposed else "no",
                writes,
            ))
            + " |"
        )
    lines.extend((
        "",
        "The machine-readable command contract additionally contains input/output schemas, timeout, idempotency, parallel-safety and full read/write globs. Run `draftpaper validate-command-contracts` before release.",
        "",
    ))
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--risk-output", type=Path, default=Path("docs/command_risk_matrix.md"))
    args = parser.parse_args(argv)
    args.risk_output.parent.mkdir(parents=True, exist_ok=True)
    args.risk_output.write_text(render_command_risk_matrix(), encoding="utf-8")
    print(args.risk_output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
