"""Generate the public CLI reference directly from CommandSpec metadata."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from draftpaper_cli.command_registry import COMMAND_SPECS


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_cli_reference() -> str:
    lines = [
        "# Draftpaper-loop CLI Reference",
        "",
        "> Generated by `python tools/generate_cli_reference.py`. Do not edit the command table manually.",
        "",
        f"This reference contains all {len(COMMAND_SPECS)} commands registered in the authoritative `CommandSpec` control plane. "
        "A namespace adapter is an explicit compatibility boundary, not a direct typed handler.",
        "",
        "| Command | Stage | Coordinator | Risk | Mutates project | Exit policy | Handler | MCP |",
        "|---|---|---|---|---:|---|---|---:|",
    ]
    for name, spec in sorted(COMMAND_SPECS.items()):
        handler = "namespace adapter" if spec.namespace_handler else f"{spec.handler_module}.{spec.handler_name}"
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{_cell(name)}`",
                    _cell(spec.formal_stage),
                    _cell(spec.coordinator),
                    _cell(spec.risk_level),
                    "yes" if spec.mutates_project else "no",
                    _cell(spec.exit_policy),
                    f"`{_cell(handler)}`",
                    "yes" if spec.mcp_exposed else "no",
                )
            )
            + " |"
        )
    lines.extend(
        (
            "",
            "## Interpretation",
            "",
            "- `human_checkpoint` commands require explicit user confirmation and are not exposed as unattended MCP actions.",
            "- `execute_science` commands may run project-local scientific code within the declared execution and write-set policy.",
            "- A non-passing hard gate returns a nonzero process status according to its exit policy.",
            "- Allowed read/write globs, input/output schemas, timeout, resource class and confirmation policy remain available from the machine-readable command-contract report.",
            "",
            "Run `draftpaper validate-command-contracts` to verify parser, registry, handler and release-manifest consistency.",
            "",
        )
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("docs/cli_reference.md"))
    args = parser.parse_args(argv)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_cli_reference(), encoding="utf-8")
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
